development:
  #Mysql Settings
  adapter: mysql
  encoding: utf8
  database: 91r_development
  username: root
  password:
  pool: 5
  
test:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: 91r_test
  username: root
  password:
  pool: 5
  
staging:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: 91r_staging
  username: root
  password:
  pool: 5
  
production:
  # Mysql Settings
  adapter: mysql
  encoding: utf8
  database: 91r_production
  username: root
  password:
  pool: 5
