development: &non_production_settings
  site_url: http://localhost:3000
  site_name: 91rentals
  admin_email: admin@91rentals.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: 91rentals
  admin_email: admin@91rentals.com
  
production:
  site_url: http://www.91rentals.com
  site_name: 91rentals
  admin_email: admin@91rentals.com
